# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dailyexpenses.ui'
#
# Created: Sat Feb 22 23:35:27 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 459)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.pageAdd = QtGui.QWidget()
        self.pageAdd.setObjectName("pageAdd")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageAdd)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutDateTime = QtGui.QHBoxLayout()
        self.layoutDateTime.setObjectName("layoutDateTime")
        self.chbCurrentDate = QtGui.QCheckBox(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbCurrentDate.sizePolicy().hasHeightForWidth())
        self.chbCurrentDate.setSizePolicy(sizePolicy)
        self.chbCurrentDate.setObjectName("chbCurrentDate")
        self.layoutDateTime.addWidget(self.chbCurrentDate)
        self.dateEdit = QtGui.QDateEdit(self.pageAdd)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.layoutDateTime.addWidget(self.dateEdit)
        self.chbCurrentTime = QtGui.QCheckBox(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbCurrentTime.sizePolicy().hasHeightForWidth())
        self.chbCurrentTime.setSizePolicy(sizePolicy)
        self.chbCurrentTime.setObjectName("chbCurrentTime")
        self.layoutDateTime.addWidget(self.chbCurrentTime)
        self.timeEdit = QtGui.QTimeEdit(self.pageAdd)
        self.timeEdit.setObjectName("timeEdit")
        self.layoutDateTime.addWidget(self.timeEdit)
        self.verticalLayout_2.addLayout(self.layoutDateTime)
        self.layoutMoney = QtGui.QHBoxLayout()
        self.layoutMoney.setObjectName("layoutMoney")
        self.rbIncome = QtGui.QRadioButton(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbIncome.sizePolicy().hasHeightForWidth())
        self.rbIncome.setSizePolicy(sizePolicy)
        self.rbIncome.setObjectName("rbIncome")
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbIncome)
        self.layoutMoney.addWidget(self.rbIncome)
        self.rbSpending = QtGui.QRadioButton(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbSpending.sizePolicy().hasHeightForWidth())
        self.rbSpending.setSizePolicy(sizePolicy)
        self.rbSpending.setChecked(True)
        self.rbSpending.setObjectName("rbSpending")
        self.buttonGroup.addButton(self.rbSpending)
        self.layoutMoney.addWidget(self.rbSpending)
        self.spinboxMoney = QtGui.QDoubleSpinBox(self.pageAdd)
        self.spinboxMoney.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinboxMoney.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinboxMoney.setMaximum(999999999.99)
        self.spinboxMoney.setObjectName("spinboxMoney")
        self.layoutMoney.addWidget(self.spinboxMoney)
        self.cbCurrency = QtGui.QComboBox(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCurrency.sizePolicy().hasHeightForWidth())
        self.cbCurrency.setSizePolicy(sizePolicy)
        self.cbCurrency.setObjectName("cbCurrency")
        self.layoutMoney.addWidget(self.cbCurrency)
        self.lblQty = QtGui.QLabel(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQty.sizePolicy().hasHeightForWidth())
        self.lblQty.setSizePolicy(sizePolicy)
        self.lblQty.setObjectName("lblQty")
        self.layoutMoney.addWidget(self.lblQty)
        self.spinboxQty = QtGui.QDoubleSpinBox(self.pageAdd)
        self.spinboxQty.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinboxQty.setMaximum(999999.99)
        self.spinboxQty.setProperty("value", 1.0)
        self.spinboxQty.setObjectName("spinboxQty")
        self.layoutMoney.addWidget(self.spinboxQty)
        self.cbUnits = QtGui.QComboBox(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbUnits.sizePolicy().hasHeightForWidth())
        self.cbUnits.setSizePolicy(sizePolicy)
        self.cbUnits.setObjectName("cbUnits")
        self.layoutMoney.addWidget(self.cbUnits)
        self.verticalLayout_2.addLayout(self.layoutMoney)
        self.layoutItem = QtGui.QHBoxLayout()
        self.layoutItem.setObjectName("layoutItem")
        self.lbItem = QtGui.QLabel(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbItem.sizePolicy().hasHeightForWidth())
        self.lbItem.setSizePolicy(sizePolicy)
        self.lbItem.setObjectName("lbItem")
        self.layoutItem.addWidget(self.lbItem)
        self.cbItem = QtGui.QComboBox(self.pageAdd)
        self.cbItem.setEditable(True)
        self.cbItem.setObjectName("cbItem")
        self.layoutItem.addWidget(self.cbItem)
        self.lbCategory = QtGui.QLabel(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbCategory.sizePolicy().hasHeightForWidth())
        self.lbCategory.setSizePolicy(sizePolicy)
        self.lbCategory.setObjectName("lbCategory")
        self.layoutItem.addWidget(self.lbCategory)
        self.cbCategory = QtGui.QComboBox(self.pageAdd)
        self.cbCategory.setEditable(True)
        self.cbCategory.setObjectName("cbCategory")
        self.layoutItem.addWidget(self.cbCategory)
        self.verticalLayout_2.addLayout(self.layoutItem)
        self.layoutWhoAndWhere = QtGui.QHBoxLayout()
        self.layoutWhoAndWhere.setObjectName("layoutWhoAndWhere")
        self.lblWhere = QtGui.QLabel(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblWhere.sizePolicy().hasHeightForWidth())
        self.lblWhere.setSizePolicy(sizePolicy)
        self.lblWhere.setObjectName("lblWhere")
        self.layoutWhoAndWhere.addWidget(self.lblWhere)
        self.cbWhere = QtGui.QComboBox(self.pageAdd)
        self.cbWhere.setEditable(True)
        self.cbWhere.setObjectName("cbWhere")
        self.layoutWhoAndWhere.addWidget(self.cbWhere)
        self.lblWho = QtGui.QLabel(self.pageAdd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblWho.sizePolicy().hasHeightForWidth())
        self.lblWho.setSizePolicy(sizePolicy)
        self.lblWho.setObjectName("lblWho")
        self.layoutWhoAndWhere.addWidget(self.lblWho)
        self.cbByWhom = QtGui.QComboBox(self.pageAdd)
        self.cbByWhom.setEditable(True)
        self.cbByWhom.setObjectName("cbByWhom")
        self.layoutWhoAndWhere.addWidget(self.cbByWhom)
        self.verticalLayout_2.addLayout(self.layoutWhoAndWhere)
        self.textNote = QtGui.QPlainTextEdit(self.pageAdd)
        self.textNote.setObjectName("textNote")
        self.verticalLayout_2.addWidget(self.textNote)
        self.layoutButton = QtGui.QHBoxLayout()
        self.layoutButton.setObjectName("layoutButton")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutButton.addItem(spacerItem)
        self.btnAdd = QtGui.QPushButton(self.pageAdd)
        self.btnAdd.setObjectName("btnAdd")
        self.layoutButton.addWidget(self.btnAdd)
        self.verticalLayout_2.addLayout(self.layoutButton)
        self.tabWidget.addTab(self.pageAdd, "")
        self.pageTable = QtGui.QWidget()
        self.pageTable.setObjectName("pageTable")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pageTable)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtGui.QTableView(self.pageTable)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.tabWidget.addTab(self.pageTable, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.chbCurrentDate.setText(QtGui.QApplication.translate("MainWindow", "current date", None, QtGui.QApplication.UnicodeUTF8))
        self.chbCurrentTime.setText(QtGui.QApplication.translate("MainWindow", "current time", None, QtGui.QApplication.UnicodeUTF8))
        self.rbIncome.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSpending.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQty.setText(QtGui.QApplication.translate("MainWindow", "qty/amount", None, QtGui.QApplication.UnicodeUTF8))
        self.lbItem.setText(QtGui.QApplication.translate("MainWindow", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.lbCategory.setText(QtGui.QApplication.translate("MainWindow", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWhere.setText(QtGui.QApplication.translate("MainWindow", "Where", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWho.setText(QtGui.QApplication.translate("MainWindow", "By whom", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pageAdd), QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pageTable), QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))

